name: Solar System Setup Workflow

on: 
 workflow_dispatch: 
 push:
    branches:  
      - main
      - 'feature/*'
env:
 MONGO_URI: ${{ vars.MONGO_URI}}
 MONGO_USERNAME: $${{ vars.MONGO_USERNAME}} 
 MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}   

jobs:
    unit-testing:
     name: Unit Test
    
    #  strategy:
    #     matrix:
    #      nodejs_version: [18, 19, 20]
    #      operating_system: [ubuntu-latest, windows-latest]
    #      exclude:
    #       - nodejs_version: 18
    #         operating_system: windows-latest
    #  runs-on: ${{ matrix.operating_system}}
     runs-on: ubuntu-latest       
     steps:  
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: setup node js version - 18
          uses: actions/setup-node@v3
          with:
           node-version: '18'

        - name: Intstall Dependencies
          run: npm install
  
        - name: Unit Test
          run: npm test

    #     - name: Upload Artifact
    #       uses: actions/upload-artifact@v3
    #       with :
    #         name: test-file
    #         path: test-file.txt 

    # code-coverage:
    #  name: Code Coverage
    #  strategy:
    #     matrix:
    #      nodejs_version: [18, 19, 20]
    #      operating_system: [ubuntu-latest, windows-latest]
    #      exclude:
    #       - nodejs_version: 18
    #         operating_system: windows-latest
    #  runs-on: ${{ matrix.operating_system}}       
    #  steps:  
    #     - name: Checkout Repo
    #       uses: actions/checkout@v4


    #     - name: Intstall Dependencies
    #       run: npm install
  
    #     - name: Unit Test
    #       run: npm run coverage

    #     - name: Upload Artifact
    #       uses: actions/upload-artifact@v3
    #       with :
    #         name: coverage-file
    #         path: coverage-file.txt 
          